#!/usr/bin/env python3
"""Extract DOT/USD price series from the `oct-10-crash` preset of
paritytech/price-oracle-testing, as a Rust module.

Two series, because they answer different questions:

- `MEDIAN`: per venue, the best bid/ask mid; DOTUSDT converted through that
  tick's median USDTUSD; then the median across venues. This is what a
  median oracle over these venues would publish: the Binance collapse is
  discarded as the outlier, and the path bottoms at -26%.
- `BINANCE`: the Binance DOTUSDT mid alone, converted the same way. It wicks
  to $0.98, -74%, which drives vaults under 100% collateralization and
  reaches the undercollateralized FinalRecovery regime. A median oracle
  would not publish this path; a single-source or manipulated one would.

Values are FixedU128 inner (price * 10^18), one per 2-second tick,
2025-10-10T21:10:00Z to 21:25:00Z.

Usage: extract_oct10.py /path/to/price-oracle-testing > ../src/oct10.rs
"""
import json, glob, os, statistics, sys

preset = os.path.join(sys.argv[1], "presets/oct-10-crash")
books = {}
for f in glob.glob(f"{preset}/*.ndjson"):
    venue, pair = os.path.basename(f).replace(".ndjson", "").split("-")
    series = {}
    for line in open(f):
        r = json.loads(line)
        if r["bids"] and r["asks"]:
            series[r["t"]] = (r["bids"][0][0] + r["asks"][0][0]) / 2
    books[(venue, pair)] = series

ticks = sorted(set().union(*books.values()))
median, binance = [], []
for t in ticks:
    usdt = statistics.median(
        [s[t] for (v, p), s in books.items() if p == "USDTUSD" and t in s] or [1.0]
    )
    dots = []
    for (v, p), s in books.items():
        if t not in s:
            continue
        if p == "DOTUSD":
            dots.append(s[t])
        elif p == "DOTUSDT":
            dots.append(s[t] * usdt)
            if v == "Binance":
                binance.append(round(s[t] * usdt * 10**18))
    if dots:
        median.append(round(statistics.median(dots) * 10**18))

manifest = json.load(open(f"{preset}/manifest.json"))

def emit(name, series):
    print(f"pub static {name}: [u128; {len(series)}] = [")
    for i in range(0, len(series), 4):
        print("    " + " ".join(f"{v}," for v in series[i : i + 4]))
    print("];\n")

print(f"""//! DOT/USD through the crash of 10 October 2025.
//!
//! Generated by `scripts/extract_oct10.py` from the `oct-10-crash` preset of
//! <https://github.com/paritytech/price-oracle-testing> (order books recorded
//! from Tardis). Do not edit; re-run the script.
//!
//! Window: {manifest['from']} to {manifest['to']}, one value per
//! {manifest['stepMs']}ms tick. Values are `FixedU128` inner: USD per DOT,
//! scaled by 10^18.
//!
//! Moments, as tick indices (tick = (t - from) / step):""")
start = int(__import__("datetime").datetime.fromisoformat(manifest["from"].replace("Z","+00:00")).timestamp()*1000)
for m in manifest["moments"]:
    at = int(__import__("datetime").datetime.fromisoformat(m["at"].replace("Z","+00:00")).timestamp()*1000)
    print(f"//! - {m['label']}: tick {(at-start)//manifest['stepMs']}")
print(f"""//!
//! `MEDIAN` is the median across venues: what a median oracle publishes.
//! The 74% Binance wick is discarded by it, so this path bottoms at -26%.
//! `BINANCE` is that single venue: the stress path, bottoming at $0.98.
""")
emit("MEDIAN", median)
emit("BINANCE", binance)
