[package]
name = "substrate-templates-fuzzers"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
resolver = "2"
members = [
    "kitchensink",
]

[workspace.dependencies]
ziggy = { version = "1.7.2", default-features = false }

rococo-runtime = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/polkadot/runtime/rococo", default-features = false }
solochain-template-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-stable2606", default-features = false }
kitchensink-runtime = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/bin/node/runtime", default-features = false }

codec = { version = "3.7.5", features = ["derive", "max-encoded-len"], default-features = false, package = "parity-scale-codec" }
scale-info = { default-features = false, version = "2.11.6", features = ["std"] }
frame-metadata = { default-features = false, version = "23.0.1", features = ["current", "decode", "std"] }
#cid = {default-features = false,  version = "0.11.2"}

node-primitives = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/bin/node/primitives", default-features = false }

frame-support = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/support", default-features = false }
frame-system = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/system", default-features = false }

sp-core = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/primitives/core", default-features = false }
sp-runtime = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/primitives/runtime", default-features = false }
sp-state-machine = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/primitives/state-machine", default-features = false }
sp-consensus-aura = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/primitives/consensus/aura", default-features = false }
sp-consensus-babe = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/primitives/consensus/babe", default-features = false }
sp-consensus-beefy = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/primitives/consensus/beefy", default-features = false }
sp-authority-discovery = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/primitives/authority-discovery", default-features = false }
sp-application-crypto = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/primitives/application-crypto", default-features = false }
sp-tracing = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/primitives/tracing", default-features = false }
sp-crypto-hashing = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/primitives/crypto/hashing", default-features = false }

polkadot-primitives = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/polkadot/primitives", default-features = false }

pallet-timestamp = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/timestamp", default-features = false }
pallet-balances = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/balances", default-features = false }
pallet-grandpa = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/grandpa", default-features = false }
pallet-staking = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/staking", default-features = false }
pallet-im-online = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/im-online", default-features = false }
pallet-referenda = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/referenda", default-features = false }
pallet-contracts = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/contracts", default-features = false }
pallet-society = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/society", default-features = false }
pallet-lottery = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/lottery", default-features = false }
pallet-utility = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/utility", default-features = false }
pallet-multisig = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/multisig", default-features = false }
pallet-remark = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/remark", default-features = false }
pallet-transaction-storage = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/transaction-storage", default-features = false }
pallet-sudo = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/sudo", default-features = false }
pallet-treasury = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/treasury", default-features = false }
pallet-collective = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/collective", default-features = false }
pallet-proxy = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/proxy", default-features = false }
pallet-broker = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/broker", default-features = false }
pallet-revive = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/revive", default-features = false }
pallet-meta-tx = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/meta-tx", default-features = false }
pallet-asset-rewards = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/asset-rewards", default-features = false }
pallet-whitelist = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/whitelist", default-features = false }
pallet-bags-list = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/bags-list", default-features = false }
pallet-recovery = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/recovery", default-features = false }
pallet-assets = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/assets", default-features = false }
pallet-bounties = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/bounties", default-features = false }
pallet-asset-conversion = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/asset-conversion", default-features = false }
pallet-vesting = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/vesting", default-features = false }
pallet-vaults = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/vaults", default-features = false }
linked-list-interface = { path = "/home/ubuntu/Work/polkadot-sdk/pusd-cross-checks/substrate/frame/linked-list/interface", default-features = false }
